#!/usr/bin/env bash

# git clone
# git clone git@github.com:Maxlufs/dotfiles.git

# directory variables
VIMDIR = "~/.dotfiles/vim"

# vim colorschemes
repoName[0]="jellybeans"; repoAddr[0]="https://github.com/nanotech/jellybeans.vim.git"
repoName[1]="molokai"; repoAddr[1]="https://github.com/tomasr/molokai.git"
repoName[2]="wombat"; repoAddr[2]="https://github.com/vim-scripts/Wombat.git "
repoName[3]="wombat256"; repoAddr[3]="https://github.com/vim-scripts/wombat256.vim.gith"

# vim plugins
repoName[4]="powerline"; repoAddr[4]="git clone https://github.com/Lokaltog/powerline.git"
repoName[5]="nerdtree"; repoAddr[5]="git clone https://github.com/scrooloose/nerdtree.git"
repoName[6]="easymotion"; repoAddr[6]="git clone https://github.com/Lokaltog/vim-easymotion.git"

################################################################################

# vim pathogen
mkdir -p $VIMDIR/autoload $VIMDIR/bundle;

echo "Installing Pathogen..." 
if [ ! -f "$VIMDIR/autoload/pathogen.vim" ]
then
	curl -Sso ~/.dotfiles/vim/autoload/pathogen.vim https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim
	echo "...done."
else
	echo "Pathogen already installed."
fi

for i in "${repoName[@]}"
do
	echo "Installing $i..."
	git clone "$i"
done

################################################################################
# TODO!!
# copy vim :helptags locations

